# --log-level
# CRITICAL = 0
# ERROR = 1
# WARNING = 2
# NOTICE = 3
# INFO = 4
# DEBUG = 5
LogLevel="DEBUG"
#LogFile="C:/temp/gocfl.log"



[DatabasePG]
Addr="localhost:1237"
Token="aslkjfs340983425sdlkffsd"
ServerCert="config/localhost.cert.pem"
ServerKey="config/localhost.key.pem"
[DatabasePG.postgres]
Connection = "host=localhost port=5000 user=%%PG_USER%% password=%%PG_PASSWORD%% dbname=mediaserver sslmode=require"
Schema = "public"
