# --log-level
# CRITICAL = 0
# ERROR = 1
# WARNING = 2
# NOTICE = 3
# INFO = 4
# DEBUG = 5
LogLevel="DEBUG"
#LogFile="C:/temp/gocfl.log"
Addr="localhost:8081"

[vfs]
    [vfs.temp] # vfs:/temp/blah
        Name="temp"
        Type="os"
        [vfs.temp.os]
            BaseDir="C:/temp"
            ZipAsFolderCache=3
    [vfs.digispace] # vfs:/digispace/blah
        Name="digispace"
        Type="sftp"
        [vfs.digispace.sftp]
            Address="localhost:2002"
            User="enge0000"
            PrivateKey=["C:/daten/keys/syncthing/putty_ed25519.priv.openssh"]
            BaseDir="/digispace"
            Sessions=5
            ZipAsFolderCache=3
    [vfs.switch_ch] # vfs:/switch_ch/blah
        Name="switch_ch"
        Type="s3"
        [vfs.switch_ch.s3]
            AccessKeyID="%%SWITCH_ACCESSKEYID%%"
            SecretAccessKey="%%SWITCH_SECRETACCESSKEY%%"
            EndPoint="s3-zh.os.switch.ch"
            UseSSL=true
            ZipAsFolderCache=5
            Bucket="testarchive"
